# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
		config.ssh.insert_key = false
	end
  config.vm.box = "xnohat/windows10lite"
  config.vm.box_version = "1.0.0"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
  end
  # config.vm.network "forwarded_port", guest: 22, host: 2223
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.hostname = "win10"
end
