# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

Vagrant.configure("2") do |config|
  common_config(config)

  config.vm.box = "boxomatic/debian-11"
  config.vm.hostname = "debian11"
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["debian"]
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox)

    virtualbox.name = "Debian11"
  end
end
