# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

vmname = "Ubuntu18.04"

Vagrant.configure("2") do |config|
  common_config(config)

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = vmname.gsub(".", "").downcase
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["debian"]
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox)
    virtualbox.name = vmname
    virtualbox.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provider "hyperv" do |hyperv, override|
    config_hyperv(config, hyperv)
    override.vm.box = "generic/ubuntu1804"
    hyperv.vmname = vmname
  end
end
