# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "gusztavvargadr/windows-11"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
  end
  # config.vm.network "forwarded_port", guest: 22, host: 2223
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.hostname = "win11"
end
