# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/settings"

vmname = "win11"

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "gusztavvargadr/windows-11"
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["win"]
  config.vm.hostname = vmname
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "2048"
  end
  # config.vm.network "forwarded_port", guest: 22, host: 2223
end
