# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

vmname = "win7"

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "designerror/windows-7"
  config.vm.network :private_network, ip: SETTINGS["private_network"]["ip"]["win"]
  config.vm.hostname = vmname
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.name = vmname
    CommonConfig::Provider::VirtualBox.configure(config, virtualbox)
  end
end
