# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

settings = YAML.load_file("../__shared__/settings.yml")
vmname = "Centos8"

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.name = vmname
    virtualbox.memory = settings["memory"]
    virtualbox.cpus = settings["cpus"]
  end
  config.vm.provider "hyperv" do |hyperv, override|
    config.vm.network "public_network", bridge: "Default Switch"
    override.vm.box = "generic/centos8"
    hyperv.vmname = vmname
    hyperv.maxmemory = settings["memory"]
    hyperv.cpus = settings["cpus"]
  end
  ssh_pub_source = ENV["WZ_SSH_PUB_KEY_PATH"]
  if ssh_pub_source
    config.vm.provision "file", source: ssh_pub_source, destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /root/.ssh/
      cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
    SHELL
  end
  config.vm.provision "shell", path: "../__scripts__/enable-ssh.sh"
  config.vm.provision "shell", path: "../__scripts__/turn-off-firewalld.sh"
  config.vm.provision "shell", path: "../__scripts__/centos/fix-yum-repos-d.sh"
end
