# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

vmname = "Centos8"

Vagrant.configure("2") do |config|
  CommonConfig.config(config)

  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["centos"]
  config.vm.provider "virtualbox" do |virtualbox|
    CommonConfig::Provider::VirtualBox.configure(config, virtualbox)
    virtualbox.name = vmname
  end
  config.vm.provider "hyperv" do |hyperv, override|
    CommonConfig::Provider::HyperV.configure(config, hyperv)
    override.vm.box = "generic/centos8"
    hyperv.vmname = vmname
  end
  config.vm.provision "shell", path: "../__scripts__/centos/yum-repos-fix.sh"
end
