# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"
require_relative "../__shared__/config"

settings = YAML.load_file("../__shared__/settings.yml")
vmname = "Centos8"

Vagrant.configure("2") do |config|
  common_config(config)

  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox, settings)
    virtualbox.name = vmname
  end
  config.vm.provider "hyperv" do |hyperv, override|
    config_hyperv(config, hyperv, settings)
    override.vm.box = "generic/centos8"
    hyperv.vmname = vmname
  end
  config.vm.provision "shell", path: "../__scripts__/centos/fix-yum-repos-d.sh"
end
