# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.network :private_network, ip: "192.168.56.12"
  config.vm.provider "virtualbox" do |pmv|
    pmv.name = "winserver2019"
    pmv.memory = 4092
    pmv.cpus = 2
  end
  config.vm.hostname = "winserver"
end
