# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu-2204"
  config.vm.network "private_network", ip: "192.168.56.9"
  config.vm.network "public_network", bridge: "Default Switch"
  config.vm.provider "virtualbox" do |pmv|
    pmv.memory = 4092
    pmv.cpus = 2
    pmv.name = "Ubuntu22.04"
    pmv.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provider "hyperv" do |pmv, override|
    override.vm.box = "generic/ubuntu2204"
    pmv.maxmemory = 4092
    pmv.cpus = 2
    pmv.vmname = "Ubuntu22.04"
  end
  ssh_pub_key_path = ENV["WZ_SSH_PUB_KEY_PATH"]
  if ssh_pub_key_path
    config.vm.provision "file", source: ssh_pub_key_path, destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /root/.ssh/
      cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
    SHELL
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo
    echo "Enabling password authentication"
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    echo
    grep '^\s*PasswordAuthentication' /etc/ssh/sshd_config
    echo
    echo "Restarting sshd service"
    systemctl restart sshd
    echo
    echo "Disabling firewalld"
    systemctl stop firewalld
    echo
  SHELL
end
