# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

settings = YAML.load_file("../__shared__/settings.yml")
vmname = "Ubuntu22.04"

Vagrant.configure("2") do |config|
  if ENV["VAGRANT_WSL"]
    config.ssh.insert_key = false
  end
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu-2204"
  config.vm.network "private_network", ip: "192.168.56.9"
  config.vm.provider "virtualbox" do |pmv|
    pmv.name = vmname
    pmv.memory = settings["memory"]
    pmv.cpus = settings["cpus"]
    pmv.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provider "hyperv" do |pmv, override|
    config.vm.network "public_network", bridge: "Default Switch"
    override.vm.box = "generic/ubuntu2204"
    pmv.vmname = vmname
    pmv.maxmemory = settings["memory"]
    pmv.cpus = settings["cpus"]
  end
  ssh_pub_key_path = ENV["WZ_SSH_PUB_KEY_PATH"]
  if ssh_pub_key_path
    config.vm.provision "file", source: ssh_pub_key_path, destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /root/.ssh/
      cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
    SHELL
  end
  config.vm.provision "shell", path: "../__scripts__/enable-ssh.sh"
  config.vm.provision "shell", path: "../__scripts__/turn-off-firewalld.sh"
end
