# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"
require_relative "../__shared__/config"

settings = YAML.load_file("../__shared__/settings.yml")
vmname = "Ubuntu22.04"

Vagrant.configure("2") do |config|
  common_config(config)

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "ubuntu-2204"
  config.vm.network "private_network", ip: settings["private_network"]["ip"]["debian"]
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox, settings)
    virtualbox.name = vmname
    virtualbox.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provider "hyperv" do |hyperv, override|
    config_hyperv(config, hyperv, settings)
    override.vm.box = "generic/ubuntu2204"
    hyperv.vmname = vmname
  end
end
