# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

Vagrant.configure("2") do |config|
  common_config(config)

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "ubuntu20.04"
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["debian"]
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox)

    virtualbox.name = "Ubuntu20.04"
    virtualbox.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
