# Type definitions for config.rb

# @param config [Vagrant::Config::V2::Root]
# @return [void]
def common_config: (untyped config) -> void

# @param config [Vagrant::Config::V2::Root]
# @param hyperv [Object]
# @return [void]
def config_hyperv: (untyped config, untyped hyperv) -> void

# @param config [Vagrant::Config::V2::Root]
# @param virtualbox [Object]
# @return [void]
def config_virtualbox: (untyped config, untyped virtualbox) -> void
