# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"
require_relative "../__common__/ubuntu/config"

vmname = "Ubuntu16.04"

Vagrant.configure("2") do |config|
  Common.config(config)

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = vmname.gsub(".", "").downcase
  config.vm.network "private_network", ip: SETTINGS["private_network"]["ip"]["debian"]
  config.vm.provider "virtualbox" do |virtualbox|
    Common.config_virtualbox(config, virtualbox)
    virtualbox.name = vmname
    Ubuntu.config(virtualbox)
  end
  config.vm.provider "hyperv" do |hyperv, override|
    Common.config_hyperv(config, hyperv)
    override.vm.box = "generic/ubuntu1604"
    hyperv.vmname = vmname
  end
end
