# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../__shared__/config"
require_relative "../__shared__/settings"

vmname = "winserver2019"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.network :private_network, ip: SETTINGS["private_network"]["ip"]["win-server"]
  config.vm.hostname = vmname
  config.vm.provider "virtualbox" do |virtualbox|
    config_virtualbox(config, virtualbox)
    virtualbox.name = vmname
  end
end
