# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	if ENV["VAGRANT_WSL"]
		config.ssh.insert_key = false
	end
	config.vm.box = "generic/openbsd6"
	config.vm.network "private_network", ip: "192.168.56.5"
	config.vm.provider "virtualbox" do |pmv|
		pmv.memory = 512
		pmv.cpus = 1
		pmv.name = "OpenBSD6"
	end
end